version: '2.0'

services:
    db:
        image: mysql:5.7
        volumes:
            - database:/var/lib/mysql
            - ./config/eve_universe.sql:/docker-entrypoint-initdb.d/dump.sql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: pathfinder
    pathfinder:
        build: .
        ports:
            - "8000:80"
            - "8443:443"

volumes:
    database: {}
